[package]
name = "zkevm_opcode_defs"
version = "1.3.1"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]

resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "circuit_pricing_generator"
path = "src/circuit_pricing_generator/main.rs"

[dependencies]
bitflags = "1.3"
lazy_static = "1.4"
ethereum-types = "0.12"
sha2 = "0.10"
